AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-3

  Sample SAM Template for aws-lambda-3

Globals:
  Function:
    Timeout: 20
Parameters:
  TopicName:
    Type: String
    Default: S3UploadNotification
  BucketName:
    Type: String
    Default: aws-image-gallery
    Description: Bucket to use SNS for
  Runtime:
    Type: String
    Default: java11
    Description: Language runtime name to use for Lambda function execution
  MemorySize:
    Type: Number
    Default: 512
    Description: Memory capacity for Lambda function execution
Resources:
  MetadataUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MetadataUpdateFunction
      Handler: com.epam.aws.lambda.App::handleRequest
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      VpcConfig:
        SecurityGroupIds:
          - sg-0b4d4276fdc900ee5
        SubnetIds:
          - subnet-01b392b00b0cd9d65
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref S3UploadTopic
  S3UploadTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref TopicName
      TopicName: !Ref TopicName
    DependsOn:
      - MetadataUpdateFunction
  S3UploadTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    DependsOn: S3UploadTopic
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 1
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - 'sns:Subscribe'
              - 'sns:Publish'
            Resource: !Ref S3UploadTopic
            Condition:
              ArnLike:
                "aws:SourceArn": !Sub 'arn:aws:s3:*:*:${BucketName}'
      Topics:
        - !Ref S3UploadTopic
  LambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt
        - MetadataUpdateFunction
        - Arn
      Protocol: lambda
      TopicArn: !Ref S3UploadTopic
    DependsOn:
      - MetadataUpdateFunction



